name: 'analytics_engineering_portfolio'
version: '1.0.0'
config-version: 2

profile: 'analytics_engineering_portfolio'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  analytics_engineering_portfolio:
    staging:
      +materialized: view
      +schema: STAGING

    intermediate:
      +materialized: view
      +schema: STAGING

    marts:
      +materialized: table
      +schema: MARTS

seeds:
  analytics_engineering_portfolio:
    +schema: RAW
